---
version: '2'
services:

  postgres:
    image: postgres
    expose:
      - 5432
    networks:
      dev:
    ports:
      - "5432:5432"
    volumes:
      - ../data/postgresql/data/:/var/lib/postgresql/data/
      - ../postgres/sql/:/sql/
      - ../sources/nistore/producers/noclook/sql/postgres.sql:/sql/postgres.sql:ro
      - ../postgres/init/init-noclook-db.sh:/docker-entrypoint-initdb.d/init-noclook-db.sh
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=docker"

  neo4j:
      image: docker.sunet.se/library/neo4j:3.0
      expose:
        - 7474
        - 7687
      networks:
        dev:
      ports:
        - "7474:7474"
        - "7687:7687"
      volumes:
        - ../data/neo4j/data:/data
        - ../neo4j/conf:/conf
      #environment:
          #- "NEO4J_AUTH=neo4j/docker"
          #- "NEO4J_dbms_allowFormatMigration=true"

networks:
  dev:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.21.0/24
          gateway: 172.16.21.1


