---
version: '2'
services:

  postgres:
    image: postgres
    expose:
      - 5432
    networks:
      dev:
        ipv4_address: 172.16.21.100
    ports:
      - "5432:5432"
    volumes:
      - ../data/postgresql/data/:/var/lib/postgresql/data/
      - ../postgres/sql/:/sql/
      - ../sources/nistore/producers/noclook/sql/postgres.sql:/sql/postgres.sql:ro
      - ../postgres/init/init-noclook-db.sh:/docker-entrypoint-initdb.d/init-noclook-db.sh
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=docker"

  neo4j:
      image: neo4j
      expose:
        - 7474
        - 7687
      networks:
        dev:
          ipv4_address: 172.16.21.110
      ports:
        - "7474:7474"
        - "7687:7687"
      volumes:
        - ../data/neo4j/data:/data
        - ../neo4j/conf:/conf
      #environment:
          #- "NEO4J_AUTH=neo4j/docker"
          #- "NEO4J_dbms_allowFormatMigration=true"

  noclook:
      image: docker.sunet.se/norduni/noclook:latest
      expose:
        - 8080
      networks:
        dev:
          ipv4_address: 172.16.21.120
      volumes:
        - ../noclook/etc/dotenv:/var/opt/norduni/norduni/src/niweb/.env:ro
        - ../noclook/etc/neo4j-only.conf:/var/opt/norduni/norduni/src/scripts/neo4j-only.conf:ro
        - ../noclook/etc/full-update.conf:/var/opt/norduni/norduni/src/scripts/full-update.conf:ro
        - ../noclook/staticfiles:/var/opt/norduni/staticfiles
        - ../noclook/log:/var/log/norduni
        - ../sources/norduni:/var/opt/source/norduni
        - ../sources/nistore:/var/opt/nistore
      environment:
        - DJANGO_SETTINGS_MODULE=niweb.settings.dev
        - CONFIG_FILE=/var/opt/norduni/norduni/src/niweb/.env
        - STATIC_ROOT=/var/opt/norduni/staticfiles
        - LOG_PATH=/var/log/norduni
        - PYTHONPATH=/var/opt/source/norduni/src/niweb:/var/opt/norduni/norduni/src/niweb
      depends_on:
        - postgres
        - neo4j

  nginx:
      image: docker.sunet.se/eduid/nginx
      expose:
        - 80
      networks:
        dev:
          ipv4_address: 172.16.21.130
      ports:
        - "80:80"
      volumes:
        - ../nginx/etc/default.conf:/etc/nginx/sites-enabled/default:ro
        - ../noclook/staticfiles:/usr/share/nginx/html/static
      depends_on:
        - noclook

networks:
  dev:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.21.0/24
          gateway: 172.16.21.1

